GET http://localhost:3000/getall

###
POST http://localhost:3000/create
Content-Type: application/json

{
"title":"all are goodkjhg and awesome and fine,,",

"name":"amardeep kumar ",
"age":20


  
}
###
GET http://localhost:3000/getones/61d2d19b2c598eb20cfc0049

###

DELETE http://localhost:3000/delete/61ceb69ad5ae134593dc847a554

###
PATCH  http://localhost:3000/update/61d2d19b2c598eb20cfc0043
Content-Type: application/json

{
  "title":"great all of yout"
  
  
}

###
POST http://localhost:3000/signup
Content-Type: application/json


{
 "name":"good name",
 "email":"amar232@gmail.com",
"password":"good120654"






}

###
POST http://localhost:3000/login
Content-Type: application/json


{

"email":"amar232@gmail.com",
"password":"good12065489"
  
}

###

POST http://localhost:3000/verify
Content-Type: application/json

{
  "email":"amar22@gmail.com",
  "verificationToken":"4525teggdx"
}


###

GET http://localhost:3000/getall
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWQ1OGI1YzE4YjJjMDBhYTQ0Y2FhYiIsImlhdCI6MTY0Mjk0ODY0MywiZXhwIjoxNjQyOTg0NjQzfQ.ac2ME7gklSKjog7lGhV9kb4GxemJKdSPUmWnXTzFAU0





###
GET http://localhost:3000/getall
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDZhMmMxMzdhODA4Y2YxZmVlMmM4OSIsImlhdCI6MTY0MTQ1NjMyMiwiZXhwIjoxNjQxNDkyMzIyfQ.C_nMnWXPbLGj9ymhbKRa_xmLjp4wbWvFHh1IBB9L_Xw

###

PATCH http://localhost:3000/changepass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWQ2MzEyMDI3M2UzOGNkZWVkMDFhNCIsImlhdCI6MTY0Mjk0NzM0NywiZXhwIjoxNjQyOTgzMzQ3fQ.9yAcXrXDs_O3o5uGf1A2olb_8fPVJX9G0op9YA8_mt8
Content-Type: application/json

{
  "currentpassword":"good120654",
  "password":"amar12345607"
}

###
PATCH   http://localhost:3000/changepass
Content-Type: application/json

{

"email":"amar22@gmail.com",
"password":"good120654",
"newPassword":"good1206548"
}

###
POST   http://localhost:3000/forgot
Content-Type: application/json

{
  "email":"a1021@gmail.com"
}

###
PATCH http://localhost:3000/reset/e579124ce9eb3aef08262b5d9530971dea4d6611aa3e0601c39a956986adc5b
Content-Type: application/json

{
  "password":"amar1234"
}

